# Extracted from https://www.theastrologyweb.com/spirit-animals

animals = {
    "alligator": "Alligator",
    "ant": "Ant",
    "badger": "Badger",
    "bat": "Bat",
    "bear": "Bear",
    "bee": "Bee",
    "blue-jay": "Blue Jay",
    "bobcat": "Bobcat",
    "buffalo": "Buffalo",
    "bull": "Bull",
    "butterfly": "Butterfly",
    "cardinal": "Cardinal",
    "cat": "Cat",
    "chameleon": "Chameleon",
    "cheetah": "Cheetah",
    "cougar-mountain-lion": "Cougar (Mountain Lion)",
    "coyote": "Coyote",
    "crab": "Crab",
    "crane": "Crane",
    "crow": "Crow",
    "deer": "Deer",
    "dog": "Dog",
    "dolphin": "Dolphin",
    "dove": "Dove",
    "dragon": "Dragon",
    "dragonfly": "Dragonfly",
    "duck": "Duck",
    "eagle": "Eagle",
    "elephant": "Elephant",
    "falcon": "Falcon",
    "firefly": "Firefly",
    "fish": "Fish",
    "flamingo": "Flamingo",
    "fox": "Fox",
    "frog": "Frog",
    "giraffe": "Giraffe",
    "goat": "Goat",
    "grasshopper": "Grasshopper",
    "groundhog": "Groundhog",
    "hawk": "Hawk",
    "hedgehog": "Hedgehog",
    "horse": "Horse",
    "hummingbird": "Hummingbird",
    "jaguar": "Jaguar",
    "jellyfish": "Jellyfish",
    "ladybug": "Ladybug",
    "leopard": "Leopard",
    "lion": "Lion",
    "lizard": "Lizard",
    "lynx": "Lynx",
    "monkey": "Monkey",
    "moose": "Moose",
    "moth": "Moth",
    "octopus": "Octopus",
    "otter": "Otter",
    "owl": "Owl",
    "panda": "Panda",
    "panther": "Panther",
    "peacock": "Peacock",
    "pig": "Pig",
    "polar-bear": "Polar Bear",
    "possum": "Possum",
    "praying-mantis": "Praying Mantis",
    "rabbit": "Rabbit",
    "raccoon": "Raccoon",
    "rat": "Rat",
    "raven": "Raven",
    "red-panda": "Red Panda",
    "rooster": "Rooster",
    "scorpion": "Scorpion",
    "seal": "Seal",
    "shark": "Shark",
    "sheep": "Sheep",
    "skunk": "Skunk",
    "sloth": "Sloth",
    "snake": "Snake",
    "snow-leopard": "Snow Leopard",
    "sparrow": "Sparrow",
    "spider": "Spider",
    "squirrel": "Squirrel",
    "swan": "Swan",
    "tiger": "Tiger",
    "turtle": "Turtle",
    "vulture": "Vulture",
    "wasp": "Wasp",
    "whale": "Whale",
    "wolf": "Wolf",
    "wolverine": "Wolverine",
    "woodpecker": "Woodpecker"
}
